INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_LIBPERSEUS libperseus-sdr)

FIND_PATH(
    LIBPERSEUS_INCLUDE_DIRS
    NAMES perseus-sdr.h
    HINTS $ENV{LIBPERSEUS_DIR}/include
        ${PC_LIBPERSEUS_INCLUDEDIR}
    PATHS /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    LIBPERSEUS_LIBRARIES
    NAMES perseus-sdr
    HINTS $ENV{LIBPERSEUS_DIR}/lib
        ${PC_LIBPERSEUS_LIBDIR}
    PATHS /usr/local/lib
          /usr/lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBPERSEUS DEFAULT_MSG LIBPERSEUS_LIBRARIES LIBPERSEUS_INCLUDE_DIRS)
MARK_AS_ADVANCED(LIBPERSEUS_LIBRARIES LIBPERSEUS_INCLUDE_DIRS)
