INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_LIBELAD libelad)

FIND_PATH(
    LIBELAD_INCLUDE_DIRS
    NAMES elad.h
    HINTS $ENV{LIBELAD_DIR}/include
        ${PC_LIBELAD_INCLUDEDIR}
    PATHS /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    LIBELAD_LIBRARIES
    NAMES elad
    HINTS $ENV{LIBELAD_DIR}/lib
        ${PC_LIBELAD_LIBDIR}
    PATHS /usr/local/lib
          /usr/lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBELAD DEFAULT_MSG LIBELAD_LIBRARIES LIBELAD_INCLUDE_DIRS)
MARK_AS_ADVANCED(LIBELAD_LIBRARIES LIBELAD_INCLUDE_DIRS)
